.TH ares 6 "January 15, 2022"
.SH NAME
higan \- Accurate Nintendo multi-system emulator
.SH SYNOPSIS
.B ares

.SH DESCRIPTION

ares is an emulator for systems from Nintendo, Sega, Sony, NEC, SNK,
Microsoft, Coleco, Bandai and Benesse. It is a descendent of higan and bsnes
and focuses on accuracy and preservation. The SNES emulation is especially
complete and polished.

.SH MORE INFO
Website: https://ares-emulator.github.io/
