.TH higan 6 "October 8, 2013"
.SH NAME
higan \- Accurate Nintendo multi-system emulator
.SH SYNOPSIS
.B higan

.SH DESCRIPTION

higan is a multi-system emulator that strives to provide the
most faithful hardware emulation possible. It focuses on accuracy and clean
code, rather than speed and special features. higan emulates systems from
Nintendo (SNES, NES, Gameboy, Gameboy Color, Gameboy Advance),
Sega (Master System, Game Gear), NEC (PC Engine, SuperGrafx) and
Bandai (WonderSwan, WonderSwan Color).

.SH CONFIGURATION

Consult the user guide (see below) for information about higans configuration.

.SH SEE ALSO

higan User Guide: /usr/share/doc/higan/higan_user_guide.html

.SH MORE INFO
Website: http://byuu.org/emulation/higan/

.SH HIGAN AUTHOR
byuu

.SH MAN PAGE AUTHORS
Brandon Barnes, Tobias Hansen
