.TH higan 6 "June 26, 2016"
.SH NAME
icarus \- Tool for importing ROMs into higans game library
.SH SYNOPSIS
.B icarus

.SH DESCRIPTION

icarus is a tool to convert ROMs of Nintendo games into the game folder
format used by the Nintendo multi-system emulator higan and to import
them into higans game library. It can be used as a standalone tool or
invoked from higans Library menu.

.SH SEE ALSO

Official documentation at https://doc.byuu.org/higan/

.SH MORE INFO
Website: http://byuu.org/emulation/higan/

.SH HIGAN AUTHOR
byuu

.SH MAN PAGE AUTHOR
Tobias Hansen
