#!/bin/bash

if test ! -d $HOME/.config/bsnes
  then
    mkdir -p $HOME/.config/bsnes
fi

if test ! -f $HOME/.config/bsnes/cheats.xml
  then
    cp /usr/share/games/bsnes/cheats.xml $HOME/.config/bsnes
fi

bsnes-bin "$@"
